// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import { type Options, Sdk } from "../sdk.gen";
import type {
  CreateItemApiV1ItemsPostData,
  CreateItemApiV1ItemsPostError,
  CreateItemApiV1ItemsPostResponse,
  CreateUserApiV1UsersPostData,
  CreateUserApiV1UsersPostError,
  CreateUserApiV1UsersPostResponse,
  DeleteItemApiV1ItemsItemIdDeleteData,
  DeleteItemApiV1ItemsItemIdDeleteError,
  DeleteItemApiV1ItemsItemIdDeleteResponse,
  GetItemApiV1ItemsItemIdGetData,
  GetSampleDataApiV1ItemsDataGetData,
  HealthCheckHealthGetData,
  UpdateItemApiV1ItemsItemIdPutData,
  UpdateItemApiV1ItemsItemIdPutError,
  UpdateItemApiV1ItemsItemIdPutResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getSampleDataApiV1ItemsDataGetQueryKey = (
  options?: Options<GetSampleDataApiV1ItemsDataGetData>,
) => createQueryKey("getSampleDataApiV1ItemsDataGet", options);

/**
 * Get Sample Data
 *
 * Get all items with Pydantic response model
 */
export const getSampleDataApiV1ItemsDataGetOptions = (
  options?: Options<GetSampleDataApiV1ItemsDataGetData>,
) =>
  queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await Sdk.__registry
        .get()
        .getSampleDataApiV1ItemsDataGet({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        });
      return data;
    },
    queryKey: getSampleDataApiV1ItemsDataGetQueryKey(options),
  });

/**
 * Delete Item
 *
 * Delete an item
 */
export const deleteItemApiV1ItemsItemIdDeleteMutation = (
  options?: Partial<Options<DeleteItemApiV1ItemsItemIdDeleteData>>,
): UseMutationOptions<
  DeleteItemApiV1ItemsItemIdDeleteResponse,
  DeleteItemApiV1ItemsItemIdDeleteError,
  Options<DeleteItemApiV1ItemsItemIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteItemApiV1ItemsItemIdDeleteResponse,
    DeleteItemApiV1ItemsItemIdDeleteError,
    Options<DeleteItemApiV1ItemsItemIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await Sdk.__registry
        .get()
        .deleteItemApiV1ItemsItemIdDelete({
          ...options,
          ...fnOptions,
          throwOnError: true,
        });
      return data;
    },
  };
  return mutationOptions;
};

export const getItemApiV1ItemsItemIdGetQueryKey = (
  options: Options<GetItemApiV1ItemsItemIdGetData>,
) => createQueryKey("getItemApiV1ItemsItemIdGet", options);

/**
 * Get Item
 *
 * Get a specific item by ID
 */
export const getItemApiV1ItemsItemIdGetOptions = (
  options: Options<GetItemApiV1ItemsItemIdGetData>,
) =>
  queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await Sdk.__registry.get().getItemApiV1ItemsItemIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getItemApiV1ItemsItemIdGetQueryKey(options),
  });

/**
 * Update Item
 *
 * Update an existing item
 */
export const updateItemApiV1ItemsItemIdPutMutation = (
  options?: Partial<Options<UpdateItemApiV1ItemsItemIdPutData>>,
): UseMutationOptions<
  UpdateItemApiV1ItemsItemIdPutResponse,
  UpdateItemApiV1ItemsItemIdPutError,
  Options<UpdateItemApiV1ItemsItemIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateItemApiV1ItemsItemIdPutResponse,
    UpdateItemApiV1ItemsItemIdPutError,
    Options<UpdateItemApiV1ItemsItemIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await Sdk.__registry
        .get()
        .updateItemApiV1ItemsItemIdPut({
          ...options,
          ...fnOptions,
          throwOnError: true,
        });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create Item
 *
 * Create a new item with Pydantic validation
 */
export const createItemApiV1ItemsPostMutation = (
  options?: Partial<Options<CreateItemApiV1ItemsPostData>>,
): UseMutationOptions<
  CreateItemApiV1ItemsPostResponse,
  CreateItemApiV1ItemsPostError,
  Options<CreateItemApiV1ItemsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateItemApiV1ItemsPostResponse,
    CreateItemApiV1ItemsPostError,
    Options<CreateItemApiV1ItemsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await Sdk.__registry.get().createItemApiV1ItemsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create User
 *
 * Create a user with email validation and password strength requirements
 */
export const createUserApiV1UsersPostMutation = (
  options?: Partial<Options<CreateUserApiV1UsersPostData>>,
): UseMutationOptions<
  CreateUserApiV1UsersPostResponse,
  CreateUserApiV1UsersPostError,
  Options<CreateUserApiV1UsersPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUserApiV1UsersPostResponse,
    CreateUserApiV1UsersPostError,
    Options<CreateUserApiV1UsersPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await Sdk.__registry.get().createUserApiV1UsersPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const healthCheckHealthGetQueryKey = (
  options?: Options<HealthCheckHealthGetData>,
) => createQueryKey("healthCheckHealthGet", options);

/**
 * Health Check
 *
 * Health check endpoint for monitoring
 */
export const healthCheckHealthGetOptions = (
  options?: Options<HealthCheckHealthGetData>,
) =>
  queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await Sdk.__registry.get().healthCheckHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthCheckHealthGetQueryKey(options),
  });
