// This file is auto-generated by @hey-api/openapi-ts

export const ApiResponseSchema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
    },
    message: {
      type: "string",
      title: "Message",
    },
    data: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Data",
    },
  },
  type: "object",
  required: ["success", "message"],
  title: "ApiResponse",
  description: "Generic API response wrapper",
} as const;

export const DataResponseSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/Item",
      },
      type: "array",
      title: "Data",
    },
    total: {
      type: "integer",
      title: "Total",
    },
    timestamp: {
      type: "string",
      format: "date-time",
      title: "Timestamp",
    },
  },
  type: "object",
  required: ["data", "total"],
  title: "DataResponse",
  description: "Response model for list of items",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const ItemSchema = {
  properties: {
    id: {
      type: "integer",
      exclusiveMinimum: 0,
      title: "Id",
      description: "Item ID must be positive",
    },
    name: {
      type: "string",
      maxLength: 100,
      minLength: 1,
      title: "Name",
      description: "Item name",
    },
    value: {
      type: "number",
      minimum: 0,
      title: "Value",
      description: "Item value must be non-negative",
    },
    category: {
      anyOf: [
        {
          $ref: "#/components/schemas/ItemCategory",
        },
        {
          type: "null",
        },
      ],
    },
    tags: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Tags",
    },
  },
  type: "object",
  required: ["id", "name", "value"],
  title: "Item",
  description: "Basic Pydantic model with validation",
  examples: [
    {
      category: "electronics",
      id: 1,
      name: "Laptop",
      tags: ["tech", "portable"],
      value: 999.99,
    },
  ],
} as const;

export const ItemCategorySchema = {
  type: "string",
  enum: ["electronics", "clothing", "food", "books"],
  title: "ItemCategory",
  description: "Example Enum for categories",
} as const;

export const ItemCreateSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 100,
      minLength: 1,
      title: "Name",
    },
    value: {
      type: "number",
      minimum: 0,
      title: "Value",
    },
    category: {
      anyOf: [
        {
          $ref: "#/components/schemas/ItemCategory",
        },
        {
          type: "null",
        },
      ],
    },
    tags: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Tags",
    },
  },
  type: "object",
  required: ["name", "value"],
  title: "ItemCreate",
  description: "Model for creating new items (without ID)",
} as const;

export const ItemUpdateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
          maxLength: 100,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    value: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Value",
    },
    category: {
      anyOf: [
        {
          $ref: "#/components/schemas/ItemCategory",
        },
        {
          type: "null",
        },
      ],
    },
    tags: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Tags",
    },
  },
  type: "object",
  title: "ItemUpdate",
  description: "Model for updating items (all fields optional)",
} as const;

export const UserSchema = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    username: {
      type: "string",
      maxLength: 50,
      minLength: 3,
      title: "Username",
    },
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    full_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
  },
  type: "object",
  required: ["id", "username", "email"],
  title: "User",
  description: "Example model with email validation",
  examples: [
    {
      email: "john@example.com",
      full_name: "John Doe",
      id: 1,
      is_active: true,
      username: "johndoe",
    },
  ],
} as const;

export const UserCreateSchema = {
  properties: {
    username: {
      type: "string",
      maxLength: 50,
      minLength: 3,
      pattern: "^[a-zA-Z0-9_]+$",
      title: "Username",
    },
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    full_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
    password: {
      type: "string",
      minLength: 8,
      title: "Password",
    },
  },
  type: "object",
  required: ["username", "email", "password"],
  title: "UserCreate",
  description: "Model for creating users",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
