// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreateItemApiV1ItemsPostData,
  CreateItemApiV1ItemsPostErrors,
  CreateItemApiV1ItemsPostResponses,
  CreateUserApiV1UsersPostData,
  CreateUserApiV1UsersPostErrors,
  CreateUserApiV1UsersPostResponses,
  DeleteItemApiV1ItemsItemIdDeleteData,
  DeleteItemApiV1ItemsItemIdDeleteErrors,
  DeleteItemApiV1ItemsItemIdDeleteResponses,
  GetItemApiV1ItemsItemIdGetData,
  GetItemApiV1ItemsItemIdGetErrors,
  GetItemApiV1ItemsItemIdGetResponses,
  GetSampleDataApiV1ItemsDataGetData,
  GetSampleDataApiV1ItemsDataGetResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
  UpdateItemApiV1ItemsItemIdPutData,
  UpdateItemApiV1ItemsItemIdPutErrors,
  UpdateItemApiV1ItemsItemIdPutResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

class HeyApiClient {
  protected client: Client;

  constructor(args?: { client?: Client }) {
    this.client = args?.client ?? client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new Sdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class Sdk extends HeyApiClient {
  public static readonly __registry = new HeyApiRegistry<Sdk>();

  constructor(args?: { client?: Client; key?: string }) {
    super(args);
    Sdk.__registry.set(this, args?.key);
  }

  /**
   * Get Sample Data
   *
   * Get all items with Pydantic response model
   */
  public getSampleDataApiV1ItemsDataGet<ThrowOnError extends boolean = false>(
    options?: Options<GetSampleDataApiV1ItemsDataGetData, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      GetSampleDataApiV1ItemsDataGetResponses,
      unknown,
      ThrowOnError
    >({
      url: "/api/v1/items/data",
      ...options,
    });
  }

  /**
   * Delete Item
   *
   * Delete an item
   */
  public deleteItemApiV1ItemsItemIdDelete<ThrowOnError extends boolean = false>(
    options: Options<DeleteItemApiV1ItemsItemIdDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).delete<
      DeleteItemApiV1ItemsItemIdDeleteResponses,
      DeleteItemApiV1ItemsItemIdDeleteErrors,
      ThrowOnError
    >({
      url: "/api/v1/items/{item_id}",
      ...options,
    });
  }

  /**
   * Get Item
   *
   * Get a specific item by ID
   */
  public getItemApiV1ItemsItemIdGet<ThrowOnError extends boolean = false>(
    options: Options<GetItemApiV1ItemsItemIdGetData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      GetItemApiV1ItemsItemIdGetResponses,
      GetItemApiV1ItemsItemIdGetErrors,
      ThrowOnError
    >({
      url: "/api/v1/items/{item_id}",
      ...options,
    });
  }

  /**
   * Update Item
   *
   * Update an existing item
   */
  public updateItemApiV1ItemsItemIdPut<ThrowOnError extends boolean = false>(
    options: Options<UpdateItemApiV1ItemsItemIdPutData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      UpdateItemApiV1ItemsItemIdPutResponses,
      UpdateItemApiV1ItemsItemIdPutErrors,
      ThrowOnError
    >({
      url: "/api/v1/items/{item_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Create Item
   *
   * Create a new item with Pydantic validation
   */
  public createItemApiV1ItemsPost<ThrowOnError extends boolean = false>(
    options: Options<CreateItemApiV1ItemsPostData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).post<
      CreateItemApiV1ItemsPostResponses,
      CreateItemApiV1ItemsPostErrors,
      ThrowOnError
    >({
      url: "/api/v1/items/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Create User
   *
   * Create a user with email validation and password strength requirements
   */
  public createUserApiV1UsersPost<ThrowOnError extends boolean = false>(
    options: Options<CreateUserApiV1UsersPostData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).post<
      CreateUserApiV1UsersPostResponses,
      CreateUserApiV1UsersPostErrors,
      ThrowOnError
    >({
      url: "/api/v1/users/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Health Check
   *
   * Health check endpoint for monitoring
   */
  public healthCheckHealthGet<ThrowOnError extends boolean = false>(
    options?: Options<HealthCheckHealthGetData, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      HealthCheckHealthGetResponses,
      unknown,
      ThrowOnError
    >({
      url: "/health",
      ...options,
    });
  }
}
