// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * ApiResponse
 *
 * Generic API response wrapper
 */
export type ApiResponse = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Message
   */
  message: string;
  /**
   * Data
   */
  data?: {
    [key: string]: unknown;
  } | null;
};

/**
 * DataResponse
 *
 * Response model for list of items
 */
export type DataResponse = {
  /**
   * Data
   */
  data: Array<Item>;
  /**
   * Total
   */
  total: number;
  /**
   * Timestamp
   */
  timestamp?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Item
 *
 * Basic Pydantic model with validation
 */
export type Item = {
  /**
   * Id
   *
   * Item ID must be positive
   */
  id: number;
  /**
   * Name
   *
   * Item name
   */
  name: string;
  /**
   * Value
   *
   * Item value must be non-negative
   */
  value: number;
  category?: ItemCategory | null;
  /**
   * Tags
   */
  tags?: Array<string>;
};

/**
 * ItemCategory
 *
 * Example Enum for categories
 */
export const ItemCategory = {
  ELECTRONICS: "electronics",
  CLOTHING: "clothing",
  FOOD: "food",
  BOOKS: "books",
} as const;

/**
 * ItemCategory
 *
 * Example Enum for categories
 */
export type ItemCategory = (typeof ItemCategory)[keyof typeof ItemCategory];

/**
 * ItemCreate
 *
 * Model for creating new items (without ID)
 */
export type ItemCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Value
   */
  value: number;
  category?: ItemCategory | null;
  /**
   * Tags
   */
  tags?: Array<string>;
};

/**
 * ItemUpdate
 *
 * Model for updating items (all fields optional)
 */
export type ItemUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Value
   */
  value?: number | null;
  category?: ItemCategory | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
};

/**
 * User
 *
 * Example model with email validation
 */
export type User = {
  /**
   * Id
   */
  id: number;
  /**
   * Username
   */
  username: string;
  /**
   * Email
   */
  email: string;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Created At
   */
  created_at?: string;
};

/**
 * UserCreate
 *
 * Model for creating users
 */
export type UserCreate = {
  /**
   * Username
   */
  username: string;
  /**
   * Email
   */
  email: string;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Password
   */
  password: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type GetSampleDataApiV1ItemsDataGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/items/data";
};

export type GetSampleDataApiV1ItemsDataGetResponses = {
  /**
   * Successful Response
   */
  200: DataResponse;
};

export type GetSampleDataApiV1ItemsDataGetResponse =
  GetSampleDataApiV1ItemsDataGetResponses[keyof GetSampleDataApiV1ItemsDataGetResponses];

export type DeleteItemApiV1ItemsItemIdDeleteData = {
  body?: never;
  path: {
    /**
     * Item Id
     */
    item_id: number;
  };
  query?: never;
  url: "/api/v1/items/{item_id}";
};

export type DeleteItemApiV1ItemsItemIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteItemApiV1ItemsItemIdDeleteError =
  DeleteItemApiV1ItemsItemIdDeleteErrors[keyof DeleteItemApiV1ItemsItemIdDeleteErrors];

export type DeleteItemApiV1ItemsItemIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse;
};

export type DeleteItemApiV1ItemsItemIdDeleteResponse =
  DeleteItemApiV1ItemsItemIdDeleteResponses[keyof DeleteItemApiV1ItemsItemIdDeleteResponses];

export type GetItemApiV1ItemsItemIdGetData = {
  body?: never;
  path: {
    /**
     * Item Id
     */
    item_id: number;
  };
  query?: never;
  url: "/api/v1/items/{item_id}";
};

export type GetItemApiV1ItemsItemIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetItemApiV1ItemsItemIdGetError =
  GetItemApiV1ItemsItemIdGetErrors[keyof GetItemApiV1ItemsItemIdGetErrors];

export type GetItemApiV1ItemsItemIdGetResponses = {
  /**
   * Successful Response
   */
  200: Item;
};

export type GetItemApiV1ItemsItemIdGetResponse =
  GetItemApiV1ItemsItemIdGetResponses[keyof GetItemApiV1ItemsItemIdGetResponses];

export type UpdateItemApiV1ItemsItemIdPutData = {
  body: ItemUpdate;
  path: {
    /**
     * Item Id
     */
    item_id: number;
  };
  query?: never;
  url: "/api/v1/items/{item_id}";
};

export type UpdateItemApiV1ItemsItemIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateItemApiV1ItemsItemIdPutError =
  UpdateItemApiV1ItemsItemIdPutErrors[keyof UpdateItemApiV1ItemsItemIdPutErrors];

export type UpdateItemApiV1ItemsItemIdPutResponses = {
  /**
   * Successful Response
   */
  200: Item;
};

export type UpdateItemApiV1ItemsItemIdPutResponse =
  UpdateItemApiV1ItemsItemIdPutResponses[keyof UpdateItemApiV1ItemsItemIdPutResponses];

export type CreateItemApiV1ItemsPostData = {
  body: ItemCreate;
  path?: never;
  query?: never;
  url: "/api/v1/items/";
};

export type CreateItemApiV1ItemsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateItemApiV1ItemsPostError =
  CreateItemApiV1ItemsPostErrors[keyof CreateItemApiV1ItemsPostErrors];

export type CreateItemApiV1ItemsPostResponses = {
  /**
   * Successful Response
   */
  201: Item;
};

export type CreateItemApiV1ItemsPostResponse =
  CreateItemApiV1ItemsPostResponses[keyof CreateItemApiV1ItemsPostResponses];

export type CreateUserApiV1UsersPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/api/v1/users/";
};

export type CreateUserApiV1UsersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserApiV1UsersPostError =
  CreateUserApiV1UsersPostErrors[keyof CreateUserApiV1UsersPostErrors];

export type CreateUserApiV1UsersPostResponses = {
  /**
   * Successful Response
   */
  201: User;
};

export type CreateUserApiV1UsersPostResponse =
  CreateUserApiV1UsersPostResponses[keyof CreateUserApiV1UsersPostResponses];

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
